version: "2.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: funthing_web:latest
    container_name: funthing_web
    restart: unless-stopped
    ports:
      - "8000:5000"
    volumes:
      - ./app:/usr/src/app/app
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: secret
      DB_NAME: funthing_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: funthing_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: funthing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

